// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.CalCom.OpenApiClient.Bookings.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BookingsGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attendees property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse_attendees>? Attendees { get; set; }
#nullable restore
#else
        public List<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse_attendees> Attendees { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The endTime property</summary>
        public DateTimeOffset? EndTime { get; set; }
        /// <summary>The eventTypeId property</summary>
        public double? EventTypeId { get; set; }
        /// <summary>The fromReschedule property</summary>
        public Guid? FromReschedule { get; set; }
        /// <summary>The id property</summary>
        public double? Id { get; set; }
        /// <summary>The payment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Payment { get; set; }
#nullable restore
#else
        public UntypedNode Payment { get; set; }
#endif
        /// <summary>The startTime property</summary>
        public DateTimeOffset? StartTime { get; set; }
        /// <summary>The timeZone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeZone { get; set; }
#nullable restore
#else
        public string TimeZone { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The uid property</summary>
        public Guid? Uid { get; set; }
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse_user? User { get; set; }
#nullable restore
#else
        public global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse_user User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse"/> and sets the default values.
        /// </summary>
        public BookingsGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attendees", n => { Attendees = n.GetCollectionOfObjectValues<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse_attendees>(global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse_attendees.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "endTime", n => { EndTime = n.GetDateTimeOffsetValue(); } },
                { "eventTypeId", n => { EventTypeId = n.GetDoubleValue(); } },
                { "fromReschedule", n => { FromReschedule = n.GetGuidValue(); } },
                { "id", n => { Id = n.GetDoubleValue(); } },
                { "payment", n => { Payment = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "startTime", n => { StartTime = n.GetDateTimeOffsetValue(); } },
                { "timeZone", n => { TimeZone = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "uid", n => { Uid = n.GetGuidValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse_user>(global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse_user.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse_attendees>("attendees", Attendees);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("endTime", EndTime);
            writer.WriteDoubleValue("eventTypeId", EventTypeId);
            writer.WriteGuidValue("fromReschedule", FromReschedule);
            writer.WriteDoubleValue("id", Id);
            writer.WriteObjectValue<UntypedNode>("payment", Payment);
            writer.WriteDateTimeOffsetValue("startTime", StartTime);
            writer.WriteStringValue("timeZone", TimeZone);
            writer.WriteStringValue("title", Title);
            writer.WriteGuidValue("uid", Uid);
            writer.WriteObjectValue<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse_user>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
