// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.CalCom.OpenApiClient.Bookings.Item.Cancel;
using Soenneker.CalCom.OpenApiClient.Bookings.Item.Recordings;
using Soenneker.CalCom.OpenApiClient.Bookings.Item.Transcripts;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.CalCom.OpenApiClient.Bookings.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \bookings\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BookingsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cancel property</summary>
        public global::Soenneker.CalCom.OpenApiClient.Bookings.Item.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::Soenneker.CalCom.OpenApiClient.Bookings.Item.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recordings property</summary>
        public global::Soenneker.CalCom.OpenApiClient.Bookings.Item.Recordings.RecordingsRequestBuilder Recordings
        {
            get => new global::Soenneker.CalCom.OpenApiClient.Bookings.Item.Recordings.RecordingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transcripts property</summary>
        public global::Soenneker.CalCom.OpenApiClient.Bookings.Item.Transcripts.TranscriptsRequestBuilder Transcripts
        {
            get => new global::Soenneker.CalCom.OpenApiClient.Bookings.Item.Transcripts.TranscriptsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BookingsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bookings/{id}?apiKey={apiKey}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BookingsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bookings/{id}?apiKey={apiKey}", rawUrl)
        {
        }
        /// <summary>
        /// Find a booking
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsItemRequestBuilder.BookingsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsItemRequestBuilder.BookingsItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse>(requestInfo, global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Edit an existing booking
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PatchAsync(global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsPatchRequestBody body, Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsItemRequestBuilder.BookingsItemRequestBuilderPatchQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PatchAsync(global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsPatchRequestBody body, Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsItemRequestBuilder.BookingsItemRequestBuilderPatchQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Find a booking
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsItemRequestBuilder.BookingsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsItemRequestBuilder.BookingsItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Edit an existing booking
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsPatchRequestBody body, Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsItemRequestBuilder.BookingsItemRequestBuilderPatchQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsPatchRequestBody body, Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsItemRequestBuilder.BookingsItemRequestBuilderPatchQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.CalCom.OpenApiClient.Bookings.Item.BookingsItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Find a booking
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BookingsItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Your API key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("apiKey")]
            public string? ApiKey { get; set; }
#nullable restore
#else
            [QueryParameter("apiKey")]
            public string ApiKey { get; set; }
#endif
        }
        /// <summary>
        /// Edit an existing booking
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BookingsItemRequestBuilderPatchQueryParameters 
        {
            /// <summary>Your API key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("apiKey")]
            public string? ApiKey { get; set; }
#nullable restore
#else
            [QueryParameter("apiKey")]
            public string ApiKey { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
