// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.CalCom.OpenApiClient.Bookings.Item.Transcripts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \bookings\{id}\transcripts\{recordingId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithRecordingItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.Bookings.Item.Transcripts.Item.WithRecordingItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRecordingItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bookings/{id}/transcripts/{recordingId}?apiKey={apiKey}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.Bookings.Item.Transcripts.Item.WithRecordingItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRecordingItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bookings/{id}/transcripts/{recordingId}?apiKey={apiKey}", rawUrl)
        {
        }
        /// <summary>
        /// Find all Cal video transcripts of that recording
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.Transcripts.Item.WithRecordingItemRequestBuilder.WithRecordingItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.Transcripts.Item.WithRecordingItemRequestBuilder.WithRecordingItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Find all Cal video transcripts of that recording
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.Transcripts.Item.WithRecordingItemRequestBuilder.WithRecordingItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Bookings.Item.Transcripts.Item.WithRecordingItemRequestBuilder.WithRecordingItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.CalCom.OpenApiClient.Bookings.Item.Transcripts.Item.WithRecordingItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.CalCom.OpenApiClient.Bookings.Item.Transcripts.Item.WithRecordingItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.CalCom.OpenApiClient.Bookings.Item.Transcripts.Item.WithRecordingItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Find all Cal video transcripts of that recording
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithRecordingItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Your API key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("apiKey")]
            public string? ApiKey { get; set; }
#nullable restore
#else
            [QueryParameter("apiKey")]
            public string ApiKey { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
