// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.CalCom.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.CalCom.OpenApiClient.Slots
{
    /// <summary>
    /// Builds and executes requests for operations under \slots
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SlotsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.Slots.SlotsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SlotsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/slots?apiKey={apiKey}&endTime={endTime}&startTime={startTime}{&eventTypeId*,eventTypeSlug*,isTeamEvent*,orgSlug*,timeZone*,usernameList*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.Slots.SlotsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SlotsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/slots?apiKey={apiKey}&endTime={endTime}&startTime={startTime}{&eventTypeId*,eventTypeSlug*,isTeamEvent*,orgSlug*,timeZone*,usernameList*}", rawUrl)
        {
        }
        /// <summary>
        /// Get all bookable slots between a datetime range
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.CalCom.OpenApiClient.Slots.SlotsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.CalCom.OpenApiClient.Models.ErrorResponse">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.CalCom.OpenApiClient.Slots.SlotsGetResponse?> GetAsSlotsGetResponseAsync(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Slots.SlotsRequestBuilder.SlotsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.CalCom.OpenApiClient.Slots.SlotsGetResponse> GetAsSlotsGetResponseAsync(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Slots.SlotsRequestBuilder.SlotsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.CalCom.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.CalCom.OpenApiClient.Slots.SlotsGetResponse>(requestInfo, global::Soenneker.CalCom.OpenApiClient.Slots.SlotsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get all bookable slots between a datetime range
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.CalCom.OpenApiClient.Slots.SlotsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.CalCom.OpenApiClient.Models.ErrorResponse">When receiving a 401 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsSlotsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.CalCom.OpenApiClient.Slots.SlotsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Slots.SlotsRequestBuilder.SlotsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.CalCom.OpenApiClient.Slots.SlotsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Slots.SlotsRequestBuilder.SlotsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.CalCom.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.CalCom.OpenApiClient.Slots.SlotsResponse>(requestInfo, global::Soenneker.CalCom.OpenApiClient.Slots.SlotsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get all bookable slots between a datetime range
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Slots.SlotsRequestBuilder.SlotsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Slots.SlotsRequestBuilder.SlotsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.CalCom.OpenApiClient.Slots.SlotsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.CalCom.OpenApiClient.Slots.SlotsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.CalCom.OpenApiClient.Slots.SlotsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get all bookable slots between a datetime range
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SlotsRequestBuilderGetQueryParameters 
        {
            /// <summary>Your API Key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("apiKey")]
            public string? ApiKey { get; set; }
#nullable restore
#else
            [QueryParameter("apiKey")]
            public string ApiKey { get; set; }
#endif
            /// <summary>End time of the slot lookup</summary>
            [QueryParameter("endTime")]
            public DateTimeOffset? EndTime { get; set; }
            /// <summary>The event type Id to fetch available slots against</summary>
            [QueryParameter("eventTypeId")]
            public double? EventTypeId { get; set; }
            /// <summary>Slug of the event type to fetch available slots against [To be used when not using eventTypeId]</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("eventTypeSlug")]
            public string? EventTypeSlug { get; set; }
#nullable restore
#else
            [QueryParameter("eventTypeSlug")]
            public string EventTypeSlug { get; set; }
#endif
            /// <summary>True if the event is a team event</summary>
            [QueryParameter("isTeamEvent")]
            public bool? IsTeamEvent { get; set; }
            /// <summary>Slug of the organization that the user belongs to, in case the user belongs to an organization [To be used when not using eventTypeId]</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orgSlug")]
            public string? OrgSlug { get; set; }
#nullable restore
#else
            [QueryParameter("orgSlug")]
            public string OrgSlug { get; set; }
#endif
            /// <summary>Start time of the slot lookup</summary>
            [QueryParameter("startTime")]
            public DateTimeOffset? StartTime { get; set; }
            /// <summary>TimeZone for the slot lookup</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("timeZone")]
            public string? TimeZone { get; set; }
#nullable restore
#else
            [QueryParameter("timeZone")]
            public string TimeZone { get; set; }
#endif
            /// <summary>An array of usernames, or team slug in case of a team event [To be used when not using eventTypeId]</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("usernameList")]
            public string[]? UsernameList { get; set; }
#nullable restore
#else
            [QueryParameter("usernameList")]
            public string[] UsernameList { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SlotsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.Slots.SlotsRequestBuilder.SlotsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
