// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.CalCom.OpenApiClient.Bookings
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BookingsPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Event description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>End time of the Event</summary>
        public DateTimeOffset? End { get; set; }
        /// <summary>ID of the event type to book</summary>
        public int? EventTypeId { get; set; }
        /// <summary>Language of the Attendee</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>Any metadata associated with the booking</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.CalCom.OpenApiClient.Bookings.BookingsPostRequestBody_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.CalCom.OpenApiClient.Bookings.BookingsPostRequestBody_metadata Metadata { get; set; }
#endif
        /// <summary>Recurring event ID if the event is recurring</summary>
        public int? RecurringEventId { get; set; }
        /// <summary>Uid of the booking to reschedule</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RescheduleUid { get; set; }
#nullable restore
#else
        public string RescheduleUid { get; set; }
#endif
        /// <summary>The responses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.CalCom.OpenApiClient.Bookings.BookingsPostRequestBody_responses? Responses { get; set; }
#nullable restore
#else
        public global::Soenneker.CalCom.OpenApiClient.Bookings.BookingsPostRequestBody_responses Responses { get; set; }
#endif
        /// <summary>The number of seats for each time slot</summary>
        public int? SeatsPerTimeSlot { get; set; }
        /// <summary>Share Attendee information in seats</summary>
        public bool? SeatsShowAttendees { get; set; }
        /// <summary>Show the number of available seats</summary>
        public bool? SeatsShowAvailabilityCount { get; set; }
        /// <summary>Start time of the Event</summary>
        public DateTimeOffset? Start { get; set; }
        /// <summary>Acceptable values one of [&quot;ACCEPTED&quot;, &quot;PENDING&quot;, &quot;CANCELLED&quot;, &quot;REJECTED&quot;]</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>TimeZone of the Attendee</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeZone { get; set; }
#nullable restore
#else
        public string TimeZone { get; set; }
#endif
        /// <summary>Booking event title</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.Bookings.BookingsPostRequestBody"/> and sets the default values.
        /// </summary>
        public BookingsPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.CalCom.OpenApiClient.Bookings.BookingsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.CalCom.OpenApiClient.Bookings.BookingsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.CalCom.OpenApiClient.Bookings.BookingsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "end", n => { End = n.GetDateTimeOffsetValue(); } },
                { "eventTypeId", n => { EventTypeId = n.GetIntValue(); } },
                { "language", n => { Language = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.CalCom.OpenApiClient.Bookings.BookingsPostRequestBody_metadata>(global::Soenneker.CalCom.OpenApiClient.Bookings.BookingsPostRequestBody_metadata.CreateFromDiscriminatorValue); } },
                { "recurringEventId", n => { RecurringEventId = n.GetIntValue(); } },
                { "rescheduleUid", n => { RescheduleUid = n.GetStringValue(); } },
                { "responses", n => { Responses = n.GetObjectValue<global::Soenneker.CalCom.OpenApiClient.Bookings.BookingsPostRequestBody_responses>(global::Soenneker.CalCom.OpenApiClient.Bookings.BookingsPostRequestBody_responses.CreateFromDiscriminatorValue); } },
                { "seatsPerTimeSlot", n => { SeatsPerTimeSlot = n.GetIntValue(); } },
                { "seatsShowAttendees", n => { SeatsShowAttendees = n.GetBoolValue(); } },
                { "seatsShowAvailabilityCount", n => { SeatsShowAvailabilityCount = n.GetBoolValue(); } },
                { "start", n => { Start = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "timeZone", n => { TimeZone = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("end", End);
            writer.WriteIntValue("eventTypeId", EventTypeId);
            writer.WriteStringValue("language", Language);
            writer.WriteObjectValue<global::Soenneker.CalCom.OpenApiClient.Bookings.BookingsPostRequestBody_metadata>("metadata", Metadata);
            writer.WriteIntValue("recurringEventId", RecurringEventId);
            writer.WriteStringValue("rescheduleUid", RescheduleUid);
            writer.WriteObjectValue<global::Soenneker.CalCom.OpenApiClient.Bookings.BookingsPostRequestBody_responses>("responses", Responses);
            writer.WriteIntValue("seatsPerTimeSlot", SeatsPerTimeSlot);
            writer.WriteBoolValue("seatsShowAttendees", SeatsShowAttendees);
            writer.WriteBoolValue("seatsShowAvailabilityCount", SeatsShowAvailabilityCount);
            writer.WriteDateTimeOffsetValue("start", Start);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("timeZone", TimeZone);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
