// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.CalCom.OpenApiClient.Webhooks.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WebhooksPatchRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Whether the webhook is active and should trigger on associated trigger events</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The events which should trigger this webhook call</summary>
        public global::Soenneker.CalCom.OpenApiClient.Webhooks.Item.WebhooksPatchRequestBody_eventTriggers? EventTriggers { get; set; }
        /// <summary>The event type ID if this webhook should be associated with only that event type</summary>
        public double? EventTypeId { get; set; }
        /// <summary>The template of the webhook&apos;s payload</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PayloadTemplate { get; set; }
#nullable restore
#else
        public string PayloadTemplate { get; set; }
#endif
        /// <summary>The secret to verify the authenticity of the received payload</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Secret { get; set; }
#nullable restore
#else
        public string Secret { get; set; }
#endif
        /// <summary>The URL to subscribe to this webhook</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubscriberUrl { get; set; }
#nullable restore
#else
        public string SubscriberUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.Webhooks.Item.WebhooksPatchRequestBody"/> and sets the default values.
        /// </summary>
        public WebhooksPatchRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.CalCom.OpenApiClient.Webhooks.Item.WebhooksPatchRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.CalCom.OpenApiClient.Webhooks.Item.WebhooksPatchRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.CalCom.OpenApiClient.Webhooks.Item.WebhooksPatchRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "eventTriggers", n => { EventTriggers = n.GetEnumValue<global::Soenneker.CalCom.OpenApiClient.Webhooks.Item.WebhooksPatchRequestBody_eventTriggers>(); } },
                { "eventTypeId", n => { EventTypeId = n.GetDoubleValue(); } },
                { "payloadTemplate", n => { PayloadTemplate = n.GetStringValue(); } },
                { "secret", n => { Secret = n.GetStringValue(); } },
                { "subscriberUrl", n => { SubscriberUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteEnumValue<global::Soenneker.CalCom.OpenApiClient.Webhooks.Item.WebhooksPatchRequestBody_eventTriggers>("eventTriggers", EventTriggers);
            writer.WriteDoubleValue("eventTypeId", EventTypeId);
            writer.WriteStringValue("payloadTemplate", PayloadTemplate);
            writer.WriteStringValue("secret", Secret);
            writer.WriteStringValue("subscriberUrl", SubscriberUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
