// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.CalCom.OpenApiClient.Webhooks.Item
{
    /// <summary>The events which should trigger this webhook call</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WebhooksPatchRequestBody_eventTriggers
    {
        [EnumMember(Value = "BOOKING_CREATED")]
        #pragma warning disable CS1591
        BOOKING_CREATED,
        #pragma warning restore CS1591
        [EnumMember(Value = "BOOKING_RESCHEDULED")]
        #pragma warning disable CS1591
        BOOKING_RESCHEDULED,
        #pragma warning restore CS1591
        [EnumMember(Value = "BOOKING_CANCELLED")]
        #pragma warning disable CS1591
        BOOKING_CANCELLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MEETING_ENDED")]
        #pragma warning disable CS1591
        MEETING_ENDED,
        #pragma warning restore CS1591
    }
}
