// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.CalCom.OpenApiClient.BookingReferences
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BookingReferencesPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bookingId property</summary>
        public bool? BookingId { get; set; }
        /// <summary>The credentialId property</summary>
        public int? CredentialId { get; set; }
        /// <summary>The deleted property</summary>
        public bool? Deleted { get; set; }
        /// <summary>The externalCalendarId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalCalendarId { get; set; }
#nullable restore
#else
        public string ExternalCalendarId { get; set; }
#endif
        /// <summary>The meetingId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MeetingId { get; set; }
#nullable restore
#else
        public string MeetingId { get; set; }
#endif
        /// <summary>The meetingPassword property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MeetingPassword { get; set; }
#nullable restore
#else
        public string MeetingPassword { get; set; }
#endif
        /// <summary>The meetingUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MeetingUrl { get; set; }
#nullable restore
#else
        public string MeetingUrl { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The uid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uid { get; set; }
#nullable restore
#else
        public string Uid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.BookingReferences.BookingReferencesPostRequestBody"/> and sets the default values.
        /// </summary>
        public BookingReferencesPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.CalCom.OpenApiClient.BookingReferences.BookingReferencesPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.CalCom.OpenApiClient.BookingReferences.BookingReferencesPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.CalCom.OpenApiClient.BookingReferences.BookingReferencesPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bookingId", n => { BookingId = n.GetBoolValue(); } },
                { "credentialId", n => { CredentialId = n.GetIntValue(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "externalCalendarId", n => { ExternalCalendarId = n.GetStringValue(); } },
                { "meetingId", n => { MeetingId = n.GetStringValue(); } },
                { "meetingPassword", n => { MeetingPassword = n.GetStringValue(); } },
                { "meetingUrl", n => { MeetingUrl = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "uid", n => { Uid = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("bookingId", BookingId);
            writer.WriteIntValue("credentialId", CredentialId);
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteStringValue("externalCalendarId", ExternalCalendarId);
            writer.WriteStringValue("meetingId", MeetingId);
            writer.WriteStringValue("meetingPassword", MeetingPassword);
            writer.WriteStringValue("meetingUrl", MeetingUrl);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("uid", Uid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
