// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.CalCom.OpenApiClient.EventTypes
{
    /// <summary>The type of scheduling if a Team event. Required for team events only</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EventTypesPostRequestBody_schedulingType
    {
        [EnumMember(Value = "ROUND_ROBIN")]
        #pragma warning disable CS1591
        ROUND_ROBIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "COLLECTIVE")]
        #pragma warning disable CS1591
        COLLECTIVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "MANAGED")]
        #pragma warning disable CS1591
        MANAGED,
        #pragma warning restore CS1591
    }
}
