// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.CalCom.OpenApiClient.EventTypes
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EventTypesPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number of minutes of buffer time after a Cal Event</summary>
        public int? AfterEventBuffer { get; set; }
        /// <summary>Number of minutes of buffer time before a Cal Event</summary>
        public int? BeforeEventBuffer { get; set; }
        /// <summary>Currency acronym. Eg- usd, eur, gbp, etc.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>Description of the event type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>If the event type should disable adding guests to the booking</summary>
        public bool? DisableGuests { get; set; }
        /// <summary>If the event type should be hidden from your public booking page</summary>
        public bool? Hidden { get; set; }
        /// <summary>If the calendar notes should be hidden from the booking</summary>
        public bool? HideCalendarNotes { get; set; }
        /// <summary>The hosts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_hosts>? Hosts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_hosts> Hosts { get; set; }
#endif
        /// <summary>Duration of the event type in minutes</summary>
        public int? Length { get; set; }
        /// <summary>A list of all available locations for the event type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Locations { get; set; }
#nullable restore
#else
        public UntypedNode Locations { get; set; }
#endif
        /// <summary>Metadata relating to event type. Pass {} if empty</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_metadata Metadata { get; set; }
#endif
        /// <summary>Minimum time in minutes before the event is bookable</summary>
        public int? MinimumBookingNotice { get; set; }
        /// <summary>EventTypeId of the parent managed event</summary>
        public int? ParentId { get; set; }
        /// <summary>If calendar days should be counted for period days</summary>
        public bool? PeriodCountCalendarDays { get; set; }
        /// <summary>Number of bookable days (Required if periodType is rolling)</summary>
        public int? PeriodDays { get; set; }
        /// <summary>End date of bookable period (Required if periodType is &apos;range&apos;)</summary>
        public DateTimeOffset? PeriodEndDate { get; set; }
        /// <summary>Start date of bookable period (Required if periodType is &apos;range&apos;)</summary>
        public DateTimeOffset? PeriodStartDate { get; set; }
        /// <summary>To decide how far into the future an invitee can book an event with you</summary>
        public global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_periodType? PeriodType { get; set; }
        /// <summary>The position of the event type on the public booking page</summary>
        public int? Position { get; set; }
        /// <summary>Price of the event type booking</summary>
        public int? Price { get; set; }
        /// <summary>If the event should recur every week/month/year with the selected frequency</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_recurringEvent? RecurringEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_recurringEvent RecurringEvent { get; set; }
#endif
        /// <summary>If the event type should require your confirmation before completing the booking</summary>
        public bool? RequiresConfirmation { get; set; }
        /// <summary>The ID of the schedule for this event type</summary>
        public double? ScheduleId { get; set; }
        /// <summary>The type of scheduling if a Team event. Required for team events only</summary>
        public global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_schedulingType? SchedulingType { get; set; }
        /// <summary>The intervals of available bookable slots in minutes</summary>
        public int? SlotInterval { get; set; }
        /// <summary>Unique slug for the event type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>A valid URL where the booker will redirect to, once the booking is completed successfully</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SuccessRedirectUrl { get; set; }
#nullable restore
#else
        public string SuccessRedirectUrl { get; set; }
#endif
        /// <summary>Team ID if the event type should belong to a team</summary>
        public int? TeamId { get; set; }
        /// <summary>Title of the event type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody"/> and sets the default values.
        /// </summary>
        public EventTypesPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "afterEventBuffer", n => { AfterEventBuffer = n.GetIntValue(); } },
                { "beforeEventBuffer", n => { BeforeEventBuffer = n.GetIntValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "disableGuests", n => { DisableGuests = n.GetBoolValue(); } },
                { "hidden", n => { Hidden = n.GetBoolValue(); } },
                { "hideCalendarNotes", n => { HideCalendarNotes = n.GetBoolValue(); } },
                { "hosts", n => { Hosts = n.GetCollectionOfObjectValues<global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_hosts>(global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_hosts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "length", n => { Length = n.GetIntValue(); } },
                { "locations", n => { Locations = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_metadata>(global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_metadata.CreateFromDiscriminatorValue); } },
                { "minimumBookingNotice", n => { MinimumBookingNotice = n.GetIntValue(); } },
                { "parentId", n => { ParentId = n.GetIntValue(); } },
                { "periodCountCalendarDays", n => { PeriodCountCalendarDays = n.GetBoolValue(); } },
                { "periodDays", n => { PeriodDays = n.GetIntValue(); } },
                { "periodEndDate", n => { PeriodEndDate = n.GetDateTimeOffsetValue(); } },
                { "periodStartDate", n => { PeriodStartDate = n.GetDateTimeOffsetValue(); } },
                { "periodType", n => { PeriodType = n.GetEnumValue<global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_periodType>(); } },
                { "position", n => { Position = n.GetIntValue(); } },
                { "price", n => { Price = n.GetIntValue(); } },
                { "recurringEvent", n => { RecurringEvent = n.GetObjectValue<global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_recurringEvent>(global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_recurringEvent.CreateFromDiscriminatorValue); } },
                { "requiresConfirmation", n => { RequiresConfirmation = n.GetBoolValue(); } },
                { "scheduleId", n => { ScheduleId = n.GetDoubleValue(); } },
                { "schedulingType", n => { SchedulingType = n.GetEnumValue<global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_schedulingType>(); } },
                { "slotInterval", n => { SlotInterval = n.GetIntValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "successRedirectUrl", n => { SuccessRedirectUrl = n.GetStringValue(); } },
                { "teamId", n => { TeamId = n.GetIntValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("afterEventBuffer", AfterEventBuffer);
            writer.WriteIntValue("beforeEventBuffer", BeforeEventBuffer);
            writer.WriteStringValue("currency", Currency);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("disableGuests", DisableGuests);
            writer.WriteBoolValue("hidden", Hidden);
            writer.WriteBoolValue("hideCalendarNotes", HideCalendarNotes);
            writer.WriteCollectionOfObjectValues<global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_hosts>("hosts", Hosts);
            writer.WriteIntValue("length", Length);
            writer.WriteObjectValue<UntypedNode>("locations", Locations);
            writer.WriteObjectValue<global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_metadata>("metadata", Metadata);
            writer.WriteIntValue("minimumBookingNotice", MinimumBookingNotice);
            writer.WriteIntValue("parentId", ParentId);
            writer.WriteBoolValue("periodCountCalendarDays", PeriodCountCalendarDays);
            writer.WriteIntValue("periodDays", PeriodDays);
            writer.WriteDateTimeOffsetValue("periodEndDate", PeriodEndDate);
            writer.WriteDateTimeOffsetValue("periodStartDate", PeriodStartDate);
            writer.WriteEnumValue<global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_periodType>("periodType", PeriodType);
            writer.WriteIntValue("position", Position);
            writer.WriteIntValue("price", Price);
            writer.WriteObjectValue<global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_recurringEvent>("recurringEvent", RecurringEvent);
            writer.WriteBoolValue("requiresConfirmation", RequiresConfirmation);
            writer.WriteDoubleValue("scheduleId", ScheduleId);
            writer.WriteEnumValue<global::Soenneker.CalCom.OpenApiClient.EventTypes.EventTypesPostRequestBody_schedulingType>("schedulingType", SchedulingType);
            writer.WriteIntValue("slotInterval", SlotInterval);
            writer.WriteStringValue("slug", Slug);
            writer.WriteStringValue("successRedirectUrl", SuccessRedirectUrl);
            writer.WriteIntValue("teamId", TeamId);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
