// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.CalCom.OpenApiClient.Teams
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TeamsPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Primary brand color for the team</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BrandColor { get; set; }
#nullable restore
#else
        public string BrandColor { get; set; }
#endif
        /// <summary>Dark variant of the primary brand color for the team</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DarkBrandColor { get; set; }
#nullable restore
#else
        public string DarkBrandColor { get; set; }
#endif
        /// <summary>Flag to hide or show the book a team member option</summary>
        public bool? HideBookATeamMember { get; set; }
        /// <summary>Flag indicating if the team is private</summary>
        public bool? IsPrivate { get; set; }
        /// <summary>Name of the team</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>ID of the team owner - only admins can set this.</summary>
        public double? OwnerId { get; set; }
        /// <summary>ID of the parent organization.</summary>
        public double? ParentId { get; set; }
        /// <summary>A unique slug that works as path for the team public page</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>Time zone of the team</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeZone { get; set; }
#nullable restore
#else
        public string TimeZone { get; set; }
#endif
        /// <summary>Starting day of the week for the team</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WeekStart { get; set; }
#nullable restore
#else
        public string WeekStart { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.Teams.TeamsPostRequestBody"/> and sets the default values.
        /// </summary>
        public TeamsPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.CalCom.OpenApiClient.Teams.TeamsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.CalCom.OpenApiClient.Teams.TeamsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.CalCom.OpenApiClient.Teams.TeamsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "brandColor", n => { BrandColor = n.GetStringValue(); } },
                { "darkBrandColor", n => { DarkBrandColor = n.GetStringValue(); } },
                { "hideBookATeamMember", n => { HideBookATeamMember = n.GetBoolValue(); } },
                { "isPrivate", n => { IsPrivate = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "ownerId", n => { OwnerId = n.GetDoubleValue(); } },
                { "parentId", n => { ParentId = n.GetDoubleValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "timeZone", n => { TimeZone = n.GetStringValue(); } },
                { "weekStart", n => { WeekStart = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("brandColor", BrandColor);
            writer.WriteStringValue("darkBrandColor", DarkBrandColor);
            writer.WriteBoolValue("hideBookATeamMember", HideBookATeamMember);
            writer.WriteBoolValue("isPrivate", IsPrivate);
            writer.WriteStringValue("name", Name);
            writer.WriteDoubleValue("ownerId", OwnerId);
            writer.WriteDoubleValue("parentId", ParentId);
            writer.WriteStringValue("slug", Slug);
            writer.WriteStringValue("timeZone", TimeZone);
            writer.WriteStringValue("weekStart", WeekStart);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
