// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.CalCom.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddBooking200ResponseBooking : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attendees property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingAttendeesItem>? Attendees { get; set; }
#nullable restore
#else
        public List<global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingAttendeesItem> Attendees { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The endTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndTime { get; set; }
#nullable restore
#else
        public string EndTime { get; set; }
#endif
        /// <summary>The eventTypeId property</summary>
        public long? EventTypeId { get; set; }
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingMetadata Metadata { get; set; }
#endif
        /// <summary>The payment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingPaymentItem>? Payment { get; set; }
#nullable restore
#else
        public List<global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingPaymentItem> Payment { get; set; }
#endif
        /// <summary>The responses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingResponses? Responses { get; set; }
#nullable restore
#else
        public global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingResponses Responses { get; set; }
#endif
        /// <summary>The startTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartTime { get; set; }
#nullable restore
#else
        public string StartTime { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The uid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uid { get; set; }
#nullable restore
#else
        public string Uid { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingUser? User { get; set; }
#nullable restore
#else
        public global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingUser User { get; set; }
#endif
        /// <summary>The userId property</summary>
        public long? UserId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBooking"/> and sets the default values.
        /// </summary>
        public AddBooking200ResponseBooking()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBooking"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBooking CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBooking();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attendees", n => { Attendees = n.GetCollectionOfObjectValues<global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingAttendeesItem>(global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingAttendeesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "endTime", n => { EndTime = n.GetStringValue(); } },
                { "eventTypeId", n => { EventTypeId = n.GetLongValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingMetadata>(global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingMetadata.CreateFromDiscriminatorValue); } },
                { "payment", n => { Payment = n.GetCollectionOfObjectValues<global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingPaymentItem>(global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingPaymentItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "responses", n => { Responses = n.GetObjectValue<global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingResponses>(global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingResponses.CreateFromDiscriminatorValue); } },
                { "startTime", n => { StartTime = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "uid", n => { Uid = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingUser>(global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingUser.CreateFromDiscriminatorValue); } },
                { "userId", n => { UserId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingAttendeesItem>("attendees", Attendees);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("endTime", EndTime);
            writer.WriteLongValue("eventTypeId", EventTypeId);
            writer.WriteLongValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingMetadata>("metadata", Metadata);
            writer.WriteCollectionOfObjectValues<global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingPaymentItem>("payment", Payment);
            writer.WriteObjectValue<global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingResponses>("responses", Responses);
            writer.WriteStringValue("startTime", StartTime);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("uid", Uid);
            writer.WriteObjectValue<global::Soenneker.CalCom.OpenApiClient.Models.AddBooking200ResponseBookingUser>("user", User);
            writer.WriteLongValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
