// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.CalCom.OpenApiClient.Models
{
    /// <summary>The events which should trigger this webhook call</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EditWebhookByIdRequestEventTriggers
    {
        [EnumMember(Value = "BOOKING_CREATED")]
        #pragma warning disable CS1591
        BookingCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "BOOKING_RESCHEDULED")]
        #pragma warning disable CS1591
        BookingRescheduled,
        #pragma warning restore CS1591
        [EnumMember(Value = "BOOKING_CANCELLED")]
        #pragma warning disable CS1591
        BookingCancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "MEETING_ENDED")]
        #pragma warning disable CS1591
        MeetingEnded,
        #pragma warning restore CS1591
    }
}
