// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.CalCom.OpenApiClient.Models
{
    /// <summary>The type of scheduling if a Team event. Required for team events only</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EditEventTypeByIdRequestSchedulingType
    {
        [EnumMember(Value = "ROUND_ROBIN")]
        #pragma warning disable CS1591
        RoundRobin,
        #pragma warning restore CS1591
        [EnumMember(Value = "COLLECTIVE")]
        #pragma warning disable CS1591
        Collective,
        #pragma warning restore CS1591
    }
}
