// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.CalCom.OpenApiClient.Models
{
    /// <summary>To decide how far into the future an invitee can book an event with you</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EditEventTypeByIdRequestPeriodType
    {
        [EnumMember(Value = "UNLIMITED")]
        #pragma warning disable CS1591
        Unlimited,
        #pragma warning restore CS1591
        [EnumMember(Value = "ROLLING")]
        #pragma warning disable CS1591
        Rolling,
        #pragma warning restore CS1591
        [EnumMember(Value = "RANGE")]
        #pragma warning disable CS1591
        Range,
        #pragma warning restore CS1591
    }
}
