// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.CalCom.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetScheduleById200ResponseScheduleAvailabilityItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The days property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<long?>? Days { get; set; }
#nullable restore
#else
        public List<long?> Days { get; set; }
#endif
        /// <summary>The endTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndTime { get; set; }
#nullable restore
#else
        public string EndTime { get; set; }
#endif
        /// <summary>The eventTypeId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.CalCom.OpenApiClient.Models.GetScheduleById200ResponseScheduleAvailabilityItemEventTypeId? EventTypeId { get; set; }
#nullable restore
#else
        public global::Soenneker.CalCom.OpenApiClient.Models.GetScheduleById200ResponseScheduleAvailabilityItemEventTypeId EventTypeId { get; set; }
#endif
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The startTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartTime { get; set; }
#nullable restore
#else
        public string StartTime { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.Models.GetScheduleById200ResponseScheduleAvailabilityItem"/> and sets the default values.
        /// </summary>
        public GetScheduleById200ResponseScheduleAvailabilityItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.CalCom.OpenApiClient.Models.GetScheduleById200ResponseScheduleAvailabilityItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.CalCom.OpenApiClient.Models.GetScheduleById200ResponseScheduleAvailabilityItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.CalCom.OpenApiClient.Models.GetScheduleById200ResponseScheduleAvailabilityItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "days", n => { Days = n.GetCollectionOfPrimitiveValues<long?>()?.AsList(); } },
                { "endTime", n => { EndTime = n.GetStringValue(); } },
                { "eventTypeId", n => { EventTypeId = n.GetObjectValue<global::Soenneker.CalCom.OpenApiClient.Models.GetScheduleById200ResponseScheduleAvailabilityItemEventTypeId>(global::Soenneker.CalCom.OpenApiClient.Models.GetScheduleById200ResponseScheduleAvailabilityItemEventTypeId.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "startTime", n => { StartTime = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<long?>("days", Days);
            writer.WriteStringValue("endTime", EndTime);
            writer.WriteObjectValue<global::Soenneker.CalCom.OpenApiClient.Models.GetScheduleById200ResponseScheduleAvailabilityItemEventTypeId>("eventTypeId", EventTypeId);
            writer.WriteLongValue("id", Id);
            writer.WriteStringValue("startTime", StartTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
