// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId
{
    /// <summary>
    /// Builds and executes requests for operations under \selected-calendars\{userId}_{integration}_{externalId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithUserId_WithIntegration_WithExternalIdRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="externalId">externalId of the selected-calendar to get</param>
        /// <param name="integration">integration of the selected calendar to get</param>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        /// <param name="userId">userId of the selected calendar to get</param>
        public WithUserId_WithIntegration_WithExternalIdRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter, int? externalId = default, string integration = "", int? userId = default) : base(requestAdapter, "{+baseurl}/selected-calendars/{userId}_{integration}_{externalId}?apiKey={apiKey}", pathParameters)
        {
            if (externalId != null) PathParameters.Add("externalId", externalId);
            if (!string.IsNullOrWhiteSpace(integration)) PathParameters.Add("integration", integration);
            if (userId != null) PathParameters.Add("userId", userId);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserId_WithIntegration_WithExternalIdRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/selected-calendars/{userId}_{integration}_{externalId}?apiKey={apiKey}", rawUrl)
        {
        }
        /// <summary>
        /// Remove a selected calendar
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder.WithUserId_WithIntegration_WithExternalIdRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder.WithUserId_WithIntegration_WithExternalIdRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Find a selected calendar by providing the compoundId(userId_integration_externalId) separated by `_`
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder.WithUserId_WithIntegration_WithExternalIdRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder.WithUserId_WithIntegration_WithExternalIdRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Edit a selected calendar
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PatchAsync(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder.WithUserId_WithIntegration_WithExternalIdRequestBuilderPatchQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PatchAsync(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder.WithUserId_WithIntegration_WithExternalIdRequestBuilderPatchQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPatchRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Remove a selected calendar
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder.WithUserId_WithIntegration_WithExternalIdRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder.WithUserId_WithIntegration_WithExternalIdRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Find a selected calendar by providing the compoundId(userId_integration_externalId) separated by `_`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder.WithUserId_WithIntegration_WithExternalIdRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder.WithUserId_WithIntegration_WithExternalIdRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Edit a selected calendar
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder.WithUserId_WithIntegration_WithExternalIdRequestBuilderPatchQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(Action<RequestConfiguration<global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder.WithUserId_WithIntegration_WithExternalIdRequestBuilderPatchQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.CalCom.OpenApiClient.SelectedCalendars.WithUserId_WithIntegration_WithExternalId.WithUserId_WithIntegration_WithExternalIdRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Remove a selected calendar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithUserId_WithIntegration_WithExternalIdRequestBuilderDeleteQueryParameters 
        {
            /// <summary>Your API Key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("apiKey")]
            public string? ApiKey { get; set; }
#nullable restore
#else
            [QueryParameter("apiKey")]
            public string ApiKey { get; set; }
#endif
        }
        /// <summary>
        /// Find a selected calendar by providing the compoundId(userId_integration_externalId) separated by `_`
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithUserId_WithIntegration_WithExternalIdRequestBuilderGetQueryParameters 
        {
            /// <summary>Your API Key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("apiKey")]
            public string? ApiKey { get; set; }
#nullable restore
#else
            [QueryParameter("apiKey")]
            public string ApiKey { get; set; }
#endif
        }
        /// <summary>
        /// Edit a selected calendar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithUserId_WithIntegration_WithExternalIdRequestBuilderPatchQueryParameters 
        {
            /// <summary>Your API Key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("apiKey")]
            public string? ApiKey { get; set; }
#nullable restore
#else
            [QueryParameter("apiKey")]
            public string ApiKey { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
